name: Test in python directory

on:
  push:
    paths:
      - 'python/**'

defaults:
  run:
    working-directory: python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: |
          pytest

