name: Test in rust directory

on:
  push:
    paths:
      - 'rust/**'

defaults:
  run:
    working-directory: rust

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: Check format
        run: |
          cargo fmt -- --check

      - name: Test
        run: |
          cargo test

