name: Test in scala directory

on:
  push:
    paths:
      - 'scala/**'

defaults:
  run:
    working-directory: scala

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.8"

      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: Build and Test
        run: |
          sbt -v +test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true

